TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 100
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  eval_strategy: epoch
  eval_steps: 100
  save_steps: 1e3
  gradient_accumulation_steps: 16